/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package br.univali.compiladores.lexico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_INTEIRA = 12;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_REAL = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int PURPOSE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int THIS = 17;
  /** RegularExpression Id. */
  int BODY = 18;
  /** RegularExpression Id. */
  int DESCRIPTION = 19;
  /** RegularExpression Id. */
  int DECLARATION = 20;
  /** RegularExpression Id. */
  int TYPE = 21;
  /** RegularExpression Id. */
  int IS = 22;
  /** RegularExpression Id. */
  int CONSTANT = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int VARIABLE = 25;
  /** RegularExpression Id. */
  int AS = 26;
  /** RegularExpression Id. */
  int INTEGER = 27;
  /** RegularExpression Id. */
  int REAL = 28;
  /** RegularExpression Id. */
  int STRING = 29;
  /** RegularExpression Id. */
  int LOGIC = 30;
  /** RegularExpression Id. */
  int DESIGNETED = 31;
  /** RegularExpression Id. */
  int TO = 32;
  /** RegularExpression Id. */
  int READ = 33;
  /** RegularExpression Id. */
  int WRITE = 34;
  /** RegularExpression Id. */
  int ALL = 35;
  /** RegularExpression Id. */
  int REPEAT = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int UNTRUE = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int OPENBRACKET = 40;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 41;
  /** RegularExpression Id. */
  int DOT = 42;
  /** RegularExpression Id. */
  int COMMA = 43;
  /** RegularExpression Id. */
  int ASSIGNMENT = 44;
  /** RegularExpression Id. */
  int PLUS = 45;
  /** RegularExpression Id. */
  int MINUS = 46;
  /** RegularExpression Id. */
  int MULTIPLY = 47;
  /** RegularExpression Id. */
  int FRACTION = 48;
  /** RegularExpression Id. */
  int POTENCY = 49;
  /** RegularExpression Id. */
  int PERCENT = 50;
  /** RegularExpression Id. */
  int OPENBRACE = 51;
  /** RegularExpression Id. */
  int CLOSEBRACE = 52;
  /** RegularExpression Id. */
  int MOD = 53;
  /** RegularExpression Id. */
  int EQUALS = 54;
  /** RegularExpression Id. */
  int DIFFERENT = 55;
  /** RegularExpression Id. */
  int LESS = 56;
  /** RegularExpression Id. */
  int GREATER = 57;
  /** RegularExpression Id. */
  int LESSEQUAL = 58;
  /** RegularExpression Id. */
  int GREATEREQUAL = 59;
  /** RegularExpression Id. */
  int AMPERSAND = 60;
  /** RegularExpression Id. */
  int PIPE = 61;
  /** RegularExpression Id. */
  int EXCLAMATION = 62;
  /** RegularExpression Id. */
  int OPENPARENTHESIS = 63;
  /** RegularExpression Id. */
  int CLOSEPARENTHESIS = 64;
  /** RegularExpression Id. */
  int LETTER_UPPER = 65;
  /** RegularExpression Id. */
  int LETTER_LOWER = 66;
  /** RegularExpression Id. */
  int LETTER_ID = 67;
  /** RegularExpression Id. */
  int DIGIT_ID = 68;
  /** RegularExpression Id. */
  int SYMBOL_UND = 69;
  /** RegularExpression Id. */
  int IDENTIFICATOR = 70;
  /** RegularExpression Id. */
  int INDENTIFICADOR_INVALIDO = 71;
  /** RegularExpression Id. */
  int STRING_DUPLA = 72;
  /** RegularExpression Id. */
  int STRING_SIMPLES = 73;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 74;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_INTEIRA_INVALIDA = 75;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_REAL_INVALIDA = 76;
  /** RegularExpression Id. */
  int STRING_INVALIDA = 77;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "<CONSTANTE_NUM_INTEIRA>",
    "<CONSTANTE_NUM_REAL>",
    "<DIGIT>",
    "\"purpose\"",
    "\"do\"",
    "\"this\"",
    "\"body\"",
    "\"description\"",
    "\"declaration\"",
    "\"type\"",
    "\"is\"",
    "\"constant\"",
    "\"and\"",
    "\"variable\"",
    "\"as\"",
    "\"integer\"",
    "\"real\"",
    "\"string\"",
    "\"logic\"",
    "\"designeted\"",
    "\"to\"",
    "\"read\"",
    "\"write\"",
    "\"all\"",
    "\"repeat\"",
    "\"true\"",
    "\"untrue\"",
    "\"false\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"{\"",
    "\"}\"",
    "\"%%\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<LETTER_UPPER>",
    "<LETTER_LOWER>",
    "<LETTER_ID>",
    "<DIGIT_ID>",
    "<SYMBOL_UND>",
    "<IDENTIFICATOR>",
    "<INDENTIFICADOR_INVALIDO>",
    "<STRING_DUPLA>",
    "<STRING_SIMPLES>",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_NUM_INTEIRA_INVALIDA>",
    "<CONSTANTE_NUM_REAL_INVALIDA>",
    "<STRING_INVALIDA>",
  };

}
