/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package br.univali.compiladores.lexico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_INTEIRA = 12;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_REAL = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int THIS = 16;
  /** RegularExpression Id. */
  int BODY = 17;
  /** RegularExpression Id. */
  int DESCRIPTION = 18;
  /** RegularExpression Id. */
  int DECLARATION = 19;
  /** RegularExpression Id. */
  int TYPE = 20;
  /** RegularExpression Id. */
  int IS = 21;
  /** RegularExpression Id. */
  int CONSTANT = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int VARIABLE = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int INTEGER = 26;
  /** RegularExpression Id. */
  int REAL = 27;
  /** RegularExpression Id. */
  int STRING = 28;
  /** RegularExpression Id. */
  int LOGIC = 29;
  /** RegularExpression Id. */
  int DESIGNATE = 30;
  /** RegularExpression Id. */
  int TO = 31;
  /** RegularExpression Id. */
  int READ = 32;
  /** RegularExpression Id. */
  int WRITE = 33;
  /** RegularExpression Id. */
  int ALL = 34;
  /** RegularExpression Id. */
  int REPEAT = 35;
  /** RegularExpression Id. */
  int TRUE = 36;
  /** RegularExpression Id. */
  int UNTRUE = 37;
  /** RegularExpression Id. */
  int OPENBRACKET = 38;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 39;
  /** RegularExpression Id. */
  int DOT = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int ASSIGNMENT = 42;
  /** RegularExpression Id. */
  int PLUS = 43;
  /** RegularExpression Id. */
  int MINUS = 44;
  /** RegularExpression Id. */
  int MULTIPLY = 45;
  /** RegularExpression Id. */
  int FRACTION = 46;
  /** RegularExpression Id. */
  int POTENCY = 47;
  /** RegularExpression Id. */
  int PERCENT = 48;
  /** RegularExpression Id. */
  int OPENBRACE = 49;
  /** RegularExpression Id. */
  int CLOSEBRACE = 50;
  /** RegularExpression Id. */
  int MOD = 51;
  /** RegularExpression Id. */
  int EQUALS = 52;
  /** RegularExpression Id. */
  int DIFFERENT = 53;
  /** RegularExpression Id. */
  int LESS = 54;
  /** RegularExpression Id. */
  int GREATER = 55;
  /** RegularExpression Id. */
  int LESSEQUAL = 56;
  /** RegularExpression Id. */
  int GREATEREQUAL = 57;
  /** RegularExpression Id. */
  int AMPERSAND = 58;
  /** RegularExpression Id. */
  int PIPE = 59;
  /** RegularExpression Id. */
  int EXCLAMATION = 60;
  /** RegularExpression Id. */
  int OPENPARENTHESIS = 61;
  /** RegularExpression Id. */
  int CLOSEPARENTHESIS = 62;
  /** RegularExpression Id. */
  int LETTER_ID = 63;
  /** RegularExpression Id. */
  int LETTER_UPPER = 64;
  /** RegularExpression Id. */
  int LETTER_LOWER = 65;
  /** RegularExpression Id. */
  int DIGIT_ID = 66;
  /** RegularExpression Id. */
  int SYMBOL_UND = 67;
  /** RegularExpression Id. */
  int IDENTIFICATOR = 68;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 69;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 70;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 71;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_INTEIRA_INVALIDA = 72;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_REAL_INVALIDA = 73;
  /** RegularExpression Id. */
  int STRING_INVALIDA = 74;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "<CONSTANTE_NUM_INTEIRA>",
    "<CONSTANTE_NUM_REAL>",
    "<DIGIT>",
    "<DO>",
    "<THIS>",
    "<BODY>",
    "<DESCRIPTION>",
    "<DECLARATION>",
    "<TYPE>",
    "<IS>",
    "<CONSTANT>",
    "<AND>",
    "<VARIABLE>",
    "<AS>",
    "<INTEGER>",
    "<REAL>",
    "<STRING>",
    "<LOGIC>",
    "<DESIGNATE>",
    "<TO>",
    "<READ>",
    "<WRITE>",
    "<ALL>",
    "<REPEAT>",
    "<TRUE>",
    "<UNTRUE>",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"{\"",
    "\"}\"",
    "\"%%\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<LETTER_ID>",
    "<LETTER_UPPER>",
    "<LETTER_LOWER>",
    "<DIGIT_ID>",
    "<SYMBOL_UND>",
    "<IDENTIFICATOR>",
    "<IDENTIFICADOR_INVALIDO>",
    "<CONSTANTE_LITERAL>",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_NUM_INTEIRA_INVALIDA>",
    "<CONSTANTE_NUM_REAL_INVALIDA>",
    "<STRING_INVALIDA>",
  };

}
