/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.compiladores.lexico;

/**
 *
 * @author biankatpas
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsMenuSeparator = new javax.swing.JSeparator();
        jtbToolBar = new javax.swing.JToolBar();
        jbNew = new javax.swing.JButton();
        jbOpen = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jsToolBarSeparator1 = new javax.swing.JToolBar.Separator();
        jbCut = new javax.swing.JButton();
        jbCopy = new javax.swing.JButton();
        jbPaste = new javax.swing.JButton();
        jsToolBarSeparator2 = new javax.swing.JToolBar.Separator();
        jbCompile = new javax.swing.JButton();
        jbRun = new javax.swing.JButton();
        jspEdit = new javax.swing.JScrollPane();
        jtaEdit = new javax.swing.JTextArea();
        jspMessage = new javax.swing.JScrollPane();
        jtaMessage = new javax.swing.JTextArea();
        jsTextAreaSeparator = new javax.swing.JSeparator();
        jmbMenuBar = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmiNew = new javax.swing.JMenuItem();
        jmiOpen = new javax.swing.JMenuItem();
        jmiSave = new javax.swing.JMenuItem();
        jmiSaveAs = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jmEdit = new javax.swing.JMenu();
        jmiCopy = new javax.swing.JMenuItem();
        jmiPaste = new javax.swing.JMenuItem();
        jmiCut = new javax.swing.JMenuItem();
        jmCompile = new javax.swing.JMenu();
        jmiCompile = new javax.swing.JMenuItem();
        jmiRun = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        jmiAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador");

        jtbToolBar.setFloatable(false);

        jbNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        jbNew.setFocusable(false);
        jbNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbNew);

        jbOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        jbOpen.setFocusable(false);
        jbOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbOpen);

        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jbSave.setFocusable(false);
        jbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbSave);
        jtbToolBar.add(jsToolBarSeparator1);

        jbCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cut.png"))); // NOI18N
        jbCut.setFocusable(false);
        jbCut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbCut);

        jbCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/copy.png"))); // NOI18N
        jbCopy.setFocusable(false);
        jbCopy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCopy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbCopy);

        jbPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paste.png"))); // NOI18N
        jbPaste.setFocusable(false);
        jbPaste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbPaste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbPaste);
        jtbToolBar.add(jsToolBarSeparator2);

        jbCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compile.png"))); // NOI18N
        jbCompile.setFocusable(false);
        jbCompile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCompile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbCompile);

        jbRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/run.png"))); // NOI18N
        jbRun.setFocusable(false);
        jbRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbRun);

        jtaEdit.setColumns(20);
        jtaEdit.setLineWrap(true);
        jtaEdit.setRows(5);
        jspEdit.setViewportView(jtaEdit);

        jtaMessage.setColumns(20);
        jtaMessage.setLineWrap(true);
        jtaMessage.setRows(5);
        jspMessage.setViewportView(jtaMessage);

        jmFile.setText("Arquivo");

        jmiNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        jmiNew.setText("Novo");
        jmFile.add(jmiNew);

        jmiOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        jmiOpen.setText("Abrir");
        jmFile.add(jmiOpen);

        jmiSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jmiSave.setText("Salvar");
        jmFile.add(jmiSave);

        jmiSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jmiSaveAs.setText("Salvar como...");
        jmFile.add(jmiSaveAs);

        jmiExit.setText("Sair");
        jmFile.add(jmiExit);

        jmbMenuBar.add(jmFile);

        jmEdit.setText("Edição");

        jmiCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/copy.png"))); // NOI18N
        jmiCopy.setText("Copiar");
        jmEdit.add(jmiCopy);

        jmiPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paste.png"))); // NOI18N
        jmiPaste.setText("Colar");
        jmEdit.add(jmiPaste);

        jmiCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cut.png"))); // NOI18N
        jmiCut.setText("Recortar");
        jmEdit.add(jmiCut);

        jmbMenuBar.add(jmEdit);

        jmCompile.setText("Compilação");

        jmiCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compile.png"))); // NOI18N
        jmiCompile.setText("Compilar");
        jmCompile.add(jmiCompile);

        jmiRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/run.png"))); // NOI18N
        jmiRun.setText("Executar");
        jmCompile.add(jmiRun);

        jmbMenuBar.add(jmCompile);

        jmHelp.setText("Ajuda");

        jmiAbout.setText("Sobre");
        jmHelp.add(jmiAbout);

        jmbMenuBar.add(jmHelp);

        setJMenuBar(jmbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsMenuSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addComponent(jspEdit)
            .addComponent(jspMessage)
            .addComponent(jsTextAreaSeparator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsMenuSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jsTextAreaSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCompile;
    private javax.swing.JButton jbCopy;
    private javax.swing.JButton jbCut;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbOpen;
    private javax.swing.JButton jbPaste;
    private javax.swing.JButton jbRun;
    private javax.swing.JButton jbSave;
    private javax.swing.JMenu jmCompile;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenuBar jmbMenuBar;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiCompile;
    private javax.swing.JMenuItem jmiCopy;
    private javax.swing.JMenuItem jmiCut;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiNew;
    private javax.swing.JMenuItem jmiOpen;
    private javax.swing.JMenuItem jmiPaste;
    private javax.swing.JMenuItem jmiRun;
    private javax.swing.JMenuItem jmiSave;
    private javax.swing.JMenuItem jmiSaveAs;
    private javax.swing.JSeparator jsMenuSeparator;
    private javax.swing.JSeparator jsTextAreaSeparator;
    private javax.swing.JToolBar.Separator jsToolBarSeparator1;
    private javax.swing.JToolBar.Separator jsToolBarSeparator2;
    private javax.swing.JScrollPane jspEdit;
    private javax.swing.JScrollPane jspMessage;
    private javax.swing.JTextArea jtaEdit;
    private javax.swing.JTextArea jtaMessage;
    private javax.swing.JToolBar jtbToolBar;
    // End of variables declaration//GEN-END:variables
}
